// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

type anyUint = byte
const (
	anyUintNONE anyUint = 0
	anyUintUint8 anyUint = 1
	anyUintUint16 anyUint = 2
	anyUintUint32 anyUint = 3
)

var EnumNamesanyUint = map[anyUint]string{
	anyUintNONE:"NONE",
	anyUintUint8:"Uint8",
	anyUintUint16:"Uint16",
	anyUintUint32:"Uint32",
}

