// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

type ArcFlag = byte
const (
	ArcFlagLargeArcA ArcFlag = 0
	ArcFlagSmallArcA ArcFlag = 1
	ArcFlagLargeArcB ArcFlag = 2
	ArcFlagSmallArcB ArcFlag = 3
)

var EnumNamesArcFlag = map[ArcFlag]string{
	ArcFlagLargeArcA:"LargeArcA",
	ArcFlagSmallArcA:"SmallArcA",
	ArcFlagLargeArcB:"LargeArcB",
	ArcFlagSmallArcB:"SmallArcB",
}

