// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Assertion struct {
	_tab flatbuffers.Table
}

func GetRootAsAssertion(buf []byte, offset flatbuffers.UOffsetT) *Assertion {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Assertion{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Assertion) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Assertion) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Assertion) Predicate(obj *IRI) *IRI {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(IRI)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Assertion) ObjectValueType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Assertion) MutateObjectValueType(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *Assertion) ObjectValue(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func AssertionStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AssertionAddPredicate(builder *flatbuffers.Builder, predicate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(predicate), 0)
}
func AssertionAddObjectValueType(builder *flatbuffers.Builder, objectValueType byte) {
	builder.PrependByteSlot(1, objectValueType, 0)
}
func AssertionAddObjectValue(builder *flatbuffers.Builder, objectValue flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(objectValue), 0)
}
func AssertionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
