// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Blending struct {
	_tab flatbuffers.Table
}

func GetRootAsBlending(buf []byte, offset flatbuffers.UOffsetT) *Blending {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Blending{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Blending) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Blending) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Blending) Operator() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Blending) MutateOperator(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func BlendingStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BlendingAddOperator(builder *flatbuffers.Builder, operator byte) {
	builder.PrependByteSlot(0, operator, 0)
}
func BlendingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
