// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

type Compositing = byte
const (
	CompositingNONE Compositing = 0
	CompositingShapeId Compositing = 1
	CompositingIllustrationId Compositing = 2
	CompositingVec2d Compositing = 3
	CompositingBlending Compositing = 4
	CompositingFlipHorizontal Compositing = 5
	CompositingInvert Compositing = 6
)

var EnumNamesCompositing = map[Compositing]string{
	CompositingNONE:"NONE",
	CompositingShapeId:"ShapeId",
	CompositingIllustrationId:"IllustrationId",
	CompositingVec2d:"Vec2d",
	CompositingBlending:"Blending",
	CompositingFlipHorizontal:"FlipHorizontal",
	CompositingInvert:"Invert",
}

