// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CubicCurve struct {
	_tab flatbuffers.Table
}

func GetRootAsCubicCurve(buf []byte, offset flatbuffers.UOffsetT) *CubicCurve {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CubicCurve{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CubicCurve) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CubicCurve) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CubicCurve) X1() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CubicCurve) MutateX1(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *CubicCurve) Y1() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CubicCurve) MutateY1(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *CubicCurve) X2() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CubicCurve) MutateX2(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *CubicCurve) Y2() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CubicCurve) MutateY2(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *CubicCurve) X() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CubicCurve) MutateX(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *CubicCurve) Y() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CubicCurve) MutateY(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func CubicCurveStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func CubicCurveAddX1(builder *flatbuffers.Builder, x1 uint32) {
	builder.PrependUint32Slot(0, x1, 0)
}
func CubicCurveAddY1(builder *flatbuffers.Builder, y1 uint32) {
	builder.PrependUint32Slot(1, y1, 0)
}
func CubicCurveAddX2(builder *flatbuffers.Builder, x2 uint32) {
	builder.PrependUint32Slot(2, x2, 0)
}
func CubicCurveAddY2(builder *flatbuffers.Builder, y2 uint32) {
	builder.PrependUint32Slot(3, y2, 0)
}
func CubicCurveAddX(builder *flatbuffers.Builder, x uint32) {
	builder.PrependUint32Slot(4, x, 0)
}
func CubicCurveAddY(builder *flatbuffers.Builder, y uint32) {
	builder.PrependUint32Slot(5, y, 0)
}
func CubicCurveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
