// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Curie struct {
	_tab flatbuffers.Table
}

func GetRootAsCurie(buf []byte, offset flatbuffers.UOffsetT) *Curie {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Curie{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Curie) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Curie) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Curie) Prefix() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CurieStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CurieAddPrefix(builder *flatbuffers.Builder, prefix flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(prefix), 0)
}
func CurieEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
