// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeletedText struct {
	_tab flatbuffers.Table
}

func GetRootAsDeletedText(buf []byte, offset flatbuffers.UOffsetT) *DeletedText {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeletedText{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DeletedText) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeletedText) Table() flatbuffers.Table {
	return rcv._tab
}

func DeletedTextStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func DeletedTextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
