// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Dim2dFraction struct {
	_tab flatbuffers.Table
}

func GetRootAsDim2dFraction(buf []byte, offset flatbuffers.UOffsetT) *Dim2dFraction {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Dim2dFraction{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Dim2dFraction) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Dim2dFraction) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Dim2dFraction) Width(obj *Fraction) *Fraction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Fraction)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Dim2dFraction) Height(obj *Fraction) *Fraction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Fraction)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func Dim2dFractionStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func Dim2dFractionAddWidth(builder *flatbuffers.Builder, width flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(width), 0)
}
func Dim2dFractionAddHeight(builder *flatbuffers.Builder, height flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(height), 0)
}
func Dim2dFractionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
