// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

type Draw = byte
const (
	DrawNONE Draw = 0
	DrawMoveTo Draw = 1
	DrawLineTo Draw = 2
	DrawHorizontal Draw = 3
	DrawVertical Draw = 4
	DrawCubicCurve Draw = 5
	DrawSmoothCubicCurve Draw = 6
	DrawQuadraticCurve Draw = 7
	DrawSmoothQuadraticCurve Draw = 8
	DrawEllipticalArc Draw = 9
	DrawPoint Draw = 10
)

var EnumNamesDraw = map[Draw]string{
	DrawNONE:"NONE",
	DrawMoveTo:"MoveTo",
	DrawLineTo:"LineTo",
	DrawHorizontal:"Horizontal",
	DrawVertical:"Vertical",
	DrawCubicCurve:"CubicCurve",
	DrawSmoothCubicCurve:"SmoothCubicCurve",
	DrawQuadraticCurve:"QuadraticCurve",
	DrawSmoothQuadraticCurve:"SmoothQuadraticCurve",
	DrawEllipticalArc:"EllipticalArc",
	DrawPoint:"Point",
}

