// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DrawItem struct {
	_tab flatbuffers.Table
}

func GetRootAsDrawItem(buf []byte, offset flatbuffers.UOffsetT) *DrawItem {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DrawItem{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DrawItem) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DrawItem) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DrawItem) ActionType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawItem) MutateActionType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *DrawItem) Action(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func DrawItemStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DrawItemAddActionType(builder *flatbuffers.Builder, actionType byte) {
	builder.PrependByteSlot(0, actionType, 0)
}
func DrawItemAddAction(builder *flatbuffers.Builder, action flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(action), 0)
}
func DrawItemEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
