// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EmphasizedText struct {
	_tab flatbuffers.Table
}

func GetRootAsEmphasizedText(buf []byte, offset flatbuffers.UOffsetT) *EmphasizedText {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EmphasizedText{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *EmphasizedText) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EmphasizedText) Table() flatbuffers.Table {
	return rcv._tab
}

func EmphasizedTextStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func EmphasizedTextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
