// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Horizontal struct {
	_tab flatbuffers.Table
}

func GetRootAsHorizontal(buf []byte, offset flatbuffers.UOffsetT) *Horizontal {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Horizontal{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Horizontal) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Horizontal) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Horizontal) X() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Horizontal) MutateX(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func HorizontalStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HorizontalAddX(builder *flatbuffers.Builder, x uint32) {
	builder.PrependUint32Slot(0, x, 0)
}
func HorizontalEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
