// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IllustrationId struct {
	_tab flatbuffers.Table
}

func GetRootAsIllustrationId(buf []byte, offset flatbuffers.UOffsetT) *IllustrationId {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IllustrationId{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *IllustrationId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IllustrationId) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IllustrationId) IllustrationId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *IllustrationId) MutateIllustrationId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func IllustrationIdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func IllustrationIdAddIllustrationId(builder *flatbuffers.Builder, illustrationId uint16) {
	builder.PrependUint16Slot(0, illustrationId, 0)
}
func IllustrationIdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
