// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InterlocatorItem struct {
	_tab flatbuffers.Table
}

func GetRootAsInterlocatorItem(buf []byte, offset flatbuffers.UOffsetT) *InterlocatorItem {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InterlocatorItem{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *InterlocatorItem) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InterlocatorItem) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InterlocatorItem) ItemType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InterlocatorItem) MutateItemType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *InterlocatorItem) Item(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func InterlocatorItemStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func InterlocatorItemAddItemType(builder *flatbuffers.Builder, itemType byte) {
	builder.PrependByteSlot(0, itemType, 0)
}
func InterlocatorItemAddItem(builder *flatbuffers.Builder, item flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(item), 0)
}
func InterlocatorItemEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
