// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

type Interlocutor = byte
const (
	InterlocutorNONE Interlocutor = 0
	InterlocutorSpeakingCharacter Interlocutor = 1
	InterlocutorThinkingCharacter Interlocutor = 2
	InterlocutorListeningCharacter Interlocutor = 3
	InterlocutorNarrator Interlocutor = 4
	InterlocutorStyleId Interlocutor = 5
)

var EnumNamesInterlocutor = map[Interlocutor]string{
	InterlocutorNONE:"NONE",
	InterlocutorSpeakingCharacter:"SpeakingCharacter",
	InterlocutorThinkingCharacter:"ThinkingCharacter",
	InterlocutorListeningCharacter:"ListeningCharacter",
	InterlocutorNarrator:"Narrator",
	InterlocutorStyleId:"StyleId",
}

