// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Invert struct {
	_tab flatbuffers.Table
}

func GetRootAsInvert(buf []byte, offset flatbuffers.UOffsetT) *Invert {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Invert{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Invert) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Invert) Table() flatbuffers.Table {
	return rcv._tab
}

func InvertStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func InvertEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
