// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IRI struct {
	_tab flatbuffers.Table
}

func GetRootAsIRI(buf []byte, offset flatbuffers.UOffsetT) *IRI {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IRI{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *IRI) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IRI) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IRI) Curie(obj *Curie) *Curie {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Curie)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *IRI) Path() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func IRIStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func IRIAddCurie(builder *flatbuffers.Builder, curie flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(curie), 0)
}
func IRIAddPath(builder *flatbuffers.Builder, path flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(path), 0)
}
func IRIEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
