// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

type Layout = byte
const (
	LayoutNONE Layout = 0
	LayoutTileLayout Layout = 1
)

var EnumNamesLayout = map[Layout]string{
	LayoutNONE:"NONE",
	LayoutTileLayout:"TileLayout",
}

