// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LineTo struct {
	_tab flatbuffers.Table
}

func GetRootAsLineTo(buf []byte, offset flatbuffers.UOffsetT) *LineTo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LineTo{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LineTo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LineTo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LineTo) X() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LineTo) MutateX(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *LineTo) Y() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LineTo) MutateY(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func LineToStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LineToAddX(builder *flatbuffers.Builder, x uint32) {
	builder.PrependUint32Slot(0, x, 0)
}
func LineToAddY(builder *flatbuffers.Builder, y uint32) {
	builder.PrependUint32Slot(1, y, 0)
}
func LineToEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
