// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Localized struct {
	_tab flatbuffers.Table
}

func GetRootAsLocalized(buf []byte, offset flatbuffers.UOffsetT) *Localized {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Localized{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Localized) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Localized) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Localized) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Localized) Language() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LocalizedStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LocalizedAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(text), 0)
}
func LocalizedAddLanguage(builder *flatbuffers.Builder, language flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(language), 0)
}
func LocalizedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
