// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

type ObjectValue = byte
const (
	ObjectValueNONE ObjectValue = 0
	ObjectValueIRI ObjectValue = 1
	ObjectValueLocalized ObjectValue = 2
	ObjectValueText ObjectValue = 3
	ObjectValueBool ObjectValue = 4
	ObjectValueUint8 ObjectValue = 5
	ObjectValueUint16 ObjectValue = 6
	ObjectValueUint32 ObjectValue = 7
	ObjectValueFloat ObjectValue = 8
	ObjectValueVector2d ObjectValue = 9
	ObjectValueVector3d ObjectValue = 10
	ObjectValueVector2dFloat ObjectValue = 11
	ObjectValueVector3dFloat ObjectValue = 12
	ObjectValueAnyURI ObjectValue = 13
	ObjectValueIsoDateTime ObjectValue = 14
	ObjectValueVectorColorRGBA ObjectValue = 15
	ObjectValueVectorFraction ObjectValue = 16
)

var EnumNamesObjectValue = map[ObjectValue]string{
	ObjectValueNONE:"NONE",
	ObjectValueIRI:"IRI",
	ObjectValueLocalized:"Localized",
	ObjectValueText:"Text",
	ObjectValueBool:"Bool",
	ObjectValueUint8:"Uint8",
	ObjectValueUint16:"Uint16",
	ObjectValueUint32:"Uint32",
	ObjectValueFloat:"Float",
	ObjectValueVector2d:"Vector2d",
	ObjectValueVector3d:"Vector3d",
	ObjectValueVector2dFloat:"Vector2dFloat",
	ObjectValueVector3dFloat:"Vector3dFloat",
	ObjectValueAnyURI:"AnyURI",
	ObjectValueIsoDateTime:"IsoDateTime",
	ObjectValueVectorColorRGBA:"VectorColorRGBA",
	ObjectValueVectorFraction:"VectorFraction",
}

