// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Point struct {
	_tab flatbuffers.Table
}

func GetRootAsPoint(buf []byte, offset flatbuffers.UOffsetT) *Point {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Point{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Point) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Point) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Point) X() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Point) MutateX(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Point) Y() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Point) MutateY(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *Point) Sid() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Point) MutateSid(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func PointStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PointAddX(builder *flatbuffers.Builder, x uint32) {
	builder.PrependUint32Slot(0, x, 0)
}
func PointAddY(builder *flatbuffers.Builder, y uint32) {
	builder.PrependUint32Slot(1, y, 0)
}
func PointAddSid(builder *flatbuffers.Builder, sid byte) {
	builder.PrependByteSlot(2, sid, 0)
}
func PointEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
