// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Publishing struct {
	_tab flatbuffers.Table
}

func GetRootAsPublishing(buf []byte, offset flatbuffers.UOffsetT) *Publishing {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Publishing{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Publishing) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Publishing) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Publishing) Metadata(obj *Metadata) *Metadata {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Metadata)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Publishing) LayoutType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Publishing) MutateLayoutType(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *Publishing) Layout(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func PublishingStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PublishingAddMetadata(builder *flatbuffers.Builder, metadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(metadata), 0)
}
func PublishingAddLayoutType(builder *flatbuffers.Builder, layoutType byte) {
	builder.PrependByteSlot(1, layoutType, 0)
}
func PublishingAddLayout(builder *flatbuffers.Builder, layout flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(layout), 0)
}
func PublishingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
