// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ShapeId struct {
	_tab flatbuffers.Table
}

func GetRootAsShapeId(buf []byte, offset flatbuffers.UOffsetT) *ShapeId {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ShapeId{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ShapeId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ShapeId) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ShapeId) ShapeId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ShapeId) MutateShapeId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func ShapeIdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ShapeIdAddShapeId(builder *flatbuffers.Builder, shapeId uint16) {
	builder.PrependUint16Slot(0, shapeId, 0)
}
func ShapeIdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
