// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SmoothQuadraticCurve struct {
	_tab flatbuffers.Table
}

func GetRootAsSmoothQuadraticCurve(buf []byte, offset flatbuffers.UOffsetT) *SmoothQuadraticCurve {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SmoothQuadraticCurve{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SmoothQuadraticCurve) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SmoothQuadraticCurve) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SmoothQuadraticCurve) X() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SmoothQuadraticCurve) MutateX(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *SmoothQuadraticCurve) Y() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SmoothQuadraticCurve) MutateY(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func SmoothQuadraticCurveStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SmoothQuadraticCurveAddX(builder *flatbuffers.Builder, x uint32) {
	builder.PrependUint32Slot(0, x, 0)
}
func SmoothQuadraticCurveAddY(builder *flatbuffers.Builder, y uint32) {
	builder.PrependUint32Slot(1, y, 0)
}
func SmoothQuadraticCurveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
