// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SmoothCubicCurve struct {
	_tab flatbuffers.Table
}

func GetRootAsSmoothCubicCurve(buf []byte, offset flatbuffers.UOffsetT) *SmoothCubicCurve {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SmoothCubicCurve{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SmoothCubicCurve) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SmoothCubicCurve) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SmoothCubicCurve) X2() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SmoothCubicCurve) MutateX2(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *SmoothCubicCurve) Y2() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SmoothCubicCurve) MutateY2(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *SmoothCubicCurve) X() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SmoothCubicCurve) MutateX(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *SmoothCubicCurve) Y() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SmoothCubicCurve) MutateY(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func SmoothCubicCurveStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func SmoothCubicCurveAddX2(builder *flatbuffers.Builder, x2 uint32) {
	builder.PrependUint32Slot(0, x2, 0)
}
func SmoothCubicCurveAddY2(builder *flatbuffers.Builder, y2 uint32) {
	builder.PrependUint32Slot(1, y2, 0)
}
func SmoothCubicCurveAddX(builder *flatbuffers.Builder, x uint32) {
	builder.PrependUint32Slot(2, x, 0)
}
func SmoothCubicCurveAddY(builder *flatbuffers.Builder, y uint32) {
	builder.PrependUint32Slot(3, y, 0)
}
func SmoothCubicCurveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
