// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SpeakingCharacter struct {
	_tab flatbuffers.Table
}

func GetRootAsSpeakingCharacter(buf []byte, offset flatbuffers.UOffsetT) *SpeakingCharacter {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpeakingCharacter{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SpeakingCharacter) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpeakingCharacter) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SpeakingCharacter) EntityId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SpeakingCharacter) MutateEntityId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func SpeakingCharacterStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SpeakingCharacterAddEntityId(builder *flatbuffers.Builder, entityId uint16) {
	builder.PrependUint16Slot(0, entityId, 0)
}
func SpeakingCharacterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
