// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SpeechId struct {
	_tab flatbuffers.Table
}

func GetRootAsSpeechId(buf []byte, offset flatbuffers.UOffsetT) *SpeechId {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpeechId{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SpeechId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpeechId) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SpeechId) SpeechId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SpeechId) MutateSpeechId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func SpeechIdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SpeechIdAddSpeechId(builder *flatbuffers.Builder, speechId uint16) {
	builder.PrependUint16Slot(0, speechId, 0)
}
func SpeechIdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
