// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StencilId struct {
	_tab flatbuffers.Table
}

func GetRootAsStencilId(buf []byte, offset flatbuffers.UOffsetT) *StencilId {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StencilId{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StencilId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StencilId) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StencilId) PanelId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StencilId) MutatePanelId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func StencilIdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StencilIdAddPanelId(builder *flatbuffers.Builder, panelId uint16) {
	builder.PrependUint16Slot(0, panelId, 0)
}
func StencilIdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
