// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StrongText struct {
	_tab flatbuffers.Table
}

func GetRootAsStrongText(buf []byte, offset flatbuffers.UOffsetT) *StrongText {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StrongText{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StrongText) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StrongText) Table() flatbuffers.Table {
	return rcv._tab
}

func StrongTextStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func StrongTextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
