// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StyleId struct {
	_tab flatbuffers.Table
}

func GetRootAsStyleId(buf []byte, offset flatbuffers.UOffsetT) *StyleId {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StyleId{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StyleId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StyleId) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StyleId) StyleId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StyleId) MutateStyleId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func StyleIdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StyleIdAddStyleId(builder *flatbuffers.Builder, styleId uint16) {
	builder.PrependUint16Slot(0, styleId, 0)
}
func StyleIdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
