// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SubscriptText struct {
	_tab flatbuffers.Table
}

func GetRootAsSubscriptText(buf []byte, offset flatbuffers.UOffsetT) *SubscriptText {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SubscriptText{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SubscriptText) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SubscriptText) Table() flatbuffers.Table {
	return rcv._tab
}

func SubscriptTextStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SubscriptTextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
