// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SuperscriptText struct {
	_tab flatbuffers.Table
}

func GetRootAsSuperscriptText(buf []byte, offset flatbuffers.UOffsetT) *SuperscriptText {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SuperscriptText{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SuperscriptText) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SuperscriptText) Table() flatbuffers.Table {
	return rcv._tab
}

func SuperscriptTextStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SuperscriptTextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
