// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Text struct {
	_tab flatbuffers.Table
}

func GetRootAsText(buf []byte, offset flatbuffers.UOffsetT) *Text {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Text{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Text) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Text) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Text) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TextStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TextAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func TextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
