// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TextSelector struct {
	_tab flatbuffers.Table
}

func GetRootAsTextSelector(buf []byte, offset flatbuffers.UOffsetT) *TextSelector {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TextSelector{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TextSelector) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TextSelector) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TextSelector) Start() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextSelector) MutateStart(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *TextSelector) End() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextSelector) MutateEnd(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func TextSelectorStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TextSelectorAddStart(builder *flatbuffers.Builder, start uint32) {
	builder.PrependUint32Slot(0, start, 0)
}
func TextSelectorAddEnd(builder *flatbuffers.Builder, end uint32) {
	builder.PrependUint32Slot(1, end, 0)
}
func TextSelectorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
