// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TileLayout struct {
	_tab flatbuffers.Table
}

func GetRootAsTileLayout(buf []byte, offset flatbuffers.UOffsetT) *TileLayout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TileLayout{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TileLayout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TileLayout) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TileLayout) Sequence(obj *TileIntableionItem, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TileLayout) SequenceLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TileLayoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TileLayoutAddSequence(builder *flatbuffers.Builder, sequence flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sequence), 0)
}
func TileLayoutStartSequenceVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TileLayoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
