// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

type TileIntableion = byte
const (
	TileIntableionNONE TileIntableion = 0
	TileIntableionSection TileIntableion = 1
	TileIntableionPage TileIntableion = 2
	TileIntableionTile TileIntableion = 3
	TileIntableionPanel TileIntableion = 4
	TileIntableionVec2dFraction TileIntableion = 5
	TileIntableionDim2dFraction TileIntableion = 6
	TileIntableionStencilId TileIntableion = 7
	TileIntableionStyleId TileIntableion = 8
	TileIntableionSpeechId TileIntableion = 9
)

var EnumNamesTileIntableion = map[TileIntableion]string{
	TileIntableionNONE:"NONE",
	TileIntableionSection:"Section",
	TileIntableionPage:"Page",
	TileIntableionTile:"Tile",
	TileIntableionPanel:"Panel",
	TileIntableionVec2dFraction:"Vec2dFraction",
	TileIntableionDim2dFraction:"Dim2dFraction",
	TileIntableionStencilId:"StencilId",
	TileIntableionStyleId:"StyleId",
	TileIntableionSpeechId:"SpeechId",
}

