// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TranscriptItem struct {
	_tab flatbuffers.Table
}

func GetRootAsTranscriptItem(buf []byte, offset flatbuffers.UOffsetT) *TranscriptItem {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TranscriptItem{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TranscriptItem) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TranscriptItem) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TranscriptItem) ItemType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TranscriptItem) MutateItemType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *TranscriptItem) Item(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func TranscriptItemStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TranscriptItemAddItemType(builder *flatbuffers.Builder, itemType byte) {
	builder.PrependByteSlot(0, itemType, 0)
}
func TranscriptItemAddItem(builder *flatbuffers.Builder, item flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(item), 0)
}
func TranscriptItemEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
