// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

type Transcript = byte
const (
	TranscriptNONE Transcript = 0
	TranscriptLocalizedTextId Transcript = 1
	TranscriptStyleId Transcript = 2
	TranscriptTextSelector Transcript = 3
	TranscriptAnnotation Transcript = 4
	TranscriptStrongText Transcript = 5
	TranscriptEmphasizedText Transcript = 6
	TranscriptDeletedText Transcript = 7
	TranscriptSubscriptText Transcript = 8
	TranscriptSuperscriptText Transcript = 9
	TranscriptMarkedText Transcript = 10
)

var EnumNamesTranscript = map[Transcript]string{
	TranscriptNONE:"NONE",
	TranscriptLocalizedTextId:"LocalizedTextId",
	TranscriptStyleId:"StyleId",
	TranscriptTextSelector:"TextSelector",
	TranscriptAnnotation:"Annotation",
	TranscriptStrongText:"StrongText",
	TranscriptEmphasizedText:"EmphasizedText",
	TranscriptDeletedText:"DeletedText",
	TranscriptSubscriptText:"SubscriptText",
	TranscriptSuperscriptText:"SuperscriptText",
	TranscriptMarkedText:"MarkedText",
}

