// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Uint16 struct {
	_tab flatbuffers.Table
}

func GetRootAsUint16(buf []byte, offset flatbuffers.UOffsetT) *Uint16 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Uint16{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Uint16) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Uint16) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Uint16) Value(j int) uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2))
	}
	return 0
}

func (rcv *Uint16) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func Uint16Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Uint16AddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func Uint16StartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func Uint16End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
