// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Vec2d struct {
	_tab flatbuffers.Table
}

func GetRootAsVec2d(buf []byte, offset flatbuffers.UOffsetT) *Vec2d {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Vec2d{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Vec2d) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vec2d) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Vec2d) X() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Vec2d) MutateX(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Vec2d) Y() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Vec2d) MutateY(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func Vec2dStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func Vec2dAddX(builder *flatbuffers.Builder, x uint32) {
	builder.PrependUint32Slot(0, x, 0)
}
func Vec2dAddY(builder *flatbuffers.Builder, y uint32) {
	builder.PrependUint32Slot(1, y, 0)
}
func Vec2dEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
