// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Vec2dFraction struct {
	_tab flatbuffers.Table
}

func GetRootAsVec2dFraction(buf []byte, offset flatbuffers.UOffsetT) *Vec2dFraction {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Vec2dFraction{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Vec2dFraction) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vec2dFraction) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Vec2dFraction) X(obj *Fraction) *Fraction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Fraction)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Vec2dFraction) Y(obj *Fraction) *Fraction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Fraction)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func Vec2dFractionStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func Vec2dFractionAddX(builder *flatbuffers.Builder, x flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(x), 0)
}
func Vec2dFractionAddY(builder *flatbuffers.Builder, y flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(y), 0)
}
func Vec2dFractionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
