// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Vec3dFloat struct {
	_tab flatbuffers.Table
}

func GetRootAsVec3dFloat(buf []byte, offset flatbuffers.UOffsetT) *Vec3dFloat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Vec3dFloat{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Vec3dFloat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vec3dFloat) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Vec3dFloat) X() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Vec3dFloat) MutateX(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *Vec3dFloat) Y() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Vec3dFloat) MutateY(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *Vec3dFloat) Z() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Vec3dFloat) MutateZ(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func Vec3dFloatStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func Vec3dFloatAddX(builder *flatbuffers.Builder, x float32) {
	builder.PrependFloat32Slot(0, x, 0.0)
}
func Vec3dFloatAddY(builder *flatbuffers.Builder, y float32) {
	builder.PrependFloat32Slot(1, y, 0.0)
}
func Vec3dFloatAddZ(builder *flatbuffers.Builder, z float32) {
	builder.PrependFloat32Slot(2, z, 0.0)
}
func Vec3dFloatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
