// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VectorColorRGBA struct {
	_tab flatbuffers.Table
}

func GetRootAsVectorColorRGBA(buf []byte, offset flatbuffers.UOffsetT) *VectorColorRGBA {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VectorColorRGBA{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *VectorColorRGBA) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VectorColorRGBA) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VectorColorRGBA) Value(obj *ColorRGBA) *ColorRGBA {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ColorRGBA)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func VectorColorRGBAStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VectorColorRGBAAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func VectorColorRGBAEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
