// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VectorFraction struct {
	_tab flatbuffers.Table
}

func GetRootAsVectorFraction(buf []byte, offset flatbuffers.UOffsetT) *VectorFraction {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VectorFraction{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *VectorFraction) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VectorFraction) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VectorFraction) Value(obj *Fraction) *Fraction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Fraction)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func VectorFractionStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VectorFractionAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func VectorFractionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
