// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Vector2d struct {
	_tab flatbuffers.Table
}

func GetRootAsVector2d(buf []byte, offset flatbuffers.UOffsetT) *Vector2d {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Vector2d{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Vector2d) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vector2d) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Vector2d) Value(obj *Vec2d) *Vec2d {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Vec2d)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func Vector2dStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Vector2dAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func Vector2dEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
