// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Vector3dFloat struct {
	_tab flatbuffers.Table
}

func GetRootAsVector3dFloat(buf []byte, offset flatbuffers.UOffsetT) *Vector3dFloat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Vector3dFloat{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Vector3dFloat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vector3dFloat) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Vector3dFloat) Value(obj *Vec3dFloat) *Vec3dFloat {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Vec3dFloat)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func Vector3dFloatStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Vector3dFloatAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func Vector3dFloatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
