// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Vertical struct {
	_tab flatbuffers.Table
}

func GetRootAsVertical(buf []byte, offset flatbuffers.UOffsetT) *Vertical {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Vertical{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Vertical) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vertical) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Vertical) Y() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Vertical) MutateY(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func VerticalStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VerticalAddY(builder *flatbuffers.Builder, y uint32) {
	builder.PrependUint32Slot(0, y, 0)
}
func VerticalEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
